# configuration for cup-service
ServiceURL =  "127.0.0.1:5571"
RootURLPattern = "/"# on target,  keep in main for the proxy
VueLibName = "vue_prod.js"
DebugVerbose = false
UseWebSocket = false
UseUnitTest = false


